# Generated by Django 2.0.7 on 2018-07-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE OR REPLACE VIEW matches_ranked_match AS
SELECT m.id, m.mmr_after, m.date, m.user_id, 
rank() OVER (PARTITION BY m.user_id ORDER BY m.date) as match_order 
FROM matches_match m;
        """),

        migrations.RunSQL("""
CREATE OR REPLACE VIEW matches_prev_match_data AS
SELECT m.*, o.id AS last_match_id, m.mmr_after - o.mmr_after AS mmr_difference
FROM matches_ranked_match m 
LEFT JOIN matches_ranked_match o ON m.user_id=o.user_id AND m.match_order = o.match_order+1;
        """)
    ]
